name: fractal build-and deploy

on:
  pull_request: []
  release:
    types: [published]
  push:
    branches:
    - main

jobs:
  build-fractal:
    permissions:
      packages: write
    env:
      container: ghcr.io/converged-computing/distributed-fractal
    runs-on: ubuntu-latest
    name: build fractal
    steps:
    - uses: actions/checkout@v4
    - name: Build Containers
      run: make docker

    - name: Tag Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ${{ env.container}}:${tag}"
        docker tag ${{ env.container }}:latest ${{ env.container }}:${tag}

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Container
      if: (github.event_name != 'pull_request')
      run: docker push ${{ env.container }} --all-tags